version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    network_mode: "host"

  kafka:
    image: wurstmeister/kafka

    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    network_mode: "host"
    depends_on:
      - zookeeper
    restart: always

  kafka2:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    network_mode: "host"
    depends_on:
      - zookeeper
    restart: always
       
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: localhost:2181
    network_mode: "host"
    depends_on:
      - kafka
      - kafka2

  # bot:
  #   build:
  #     context: bot_notification/
  #     dockerfile: Dockerfile
  #   network_mode: "host"
  #   depends_on:
  #     - kafka
  #     - kafka2
  
  email:
    build:
      context: email_notification/
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - kafka-ui